lib: [
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/Jose.a"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/Jose.cma"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/Jose.cmxa"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/Jose.cmxs"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/Jwk.ml"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/Jwk.mli"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/Jwks.re"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/Jwks.rei"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/Jwt.re"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/Jwt.rei"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/META"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/Utils.re"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/dune-package"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/framework/TestFramework.a" {"framework/TestFramework.a"}
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/framework/TestFramework.cma" {"framework/TestFramework.cma"}
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/framework/TestFramework.cmi" {"framework/TestFramework.cmi"}
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/framework/TestFramework.cmt" {"framework/TestFramework.cmt"}
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/framework/TestFramework.cmx" {"framework/TestFramework.cmx"}
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/framework/TestFramework.cmxa" {"framework/TestFramework.cmxa"}
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/framework/TestFramework.cmxs" {"framework/TestFramework.cmxs"}
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/framework/TestFramework.re" {"framework/TestFramework.re"}
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/jose.cmi"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/jose.cmt"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/jose.cmx"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/jose.ml"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/jose__Jwk.cmi"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/jose__Jwk.cmt"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/jose__Jwk.cmti"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/jose__Jwk.cmx"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/jose__Jwks.cmi"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/jose__Jwks.cmt"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/jose__Jwks.cmti"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/jose__Jwks.cmx"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/jose__Jwt.cmi"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/jose__Jwt.cmt"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/jose__Jwt.cmti"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/jose__Jwt.cmx"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/jose__Utils.cmi"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/jose__Utils.cmt"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/jose__Utils.cmx"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/opam"
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/test/Fixtures.re" {"test/Fixtures.re"}
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/test/JWKTest.re" {"test/JWKTest.re"}
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/test/JWTTest.re" {"test/JWTTest.re"}
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/test/jose_test.a" {"test/jose_test.a"}
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/test/jose_test.cma" {"test/jose_test.cma"}
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/test/jose_test.cmi" {"test/jose_test.cmi"}
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/test/jose_test.cmt" {"test/jose_test.cmt"}
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/test/jose_test.cmx" {"test/jose_test.cmx"}
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/test/jose_test.cmxa" {"test/jose_test.cmxa"}
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/test/jose_test.cmxs" {"test/jose_test.cmxs"}
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/test/jose_test.ml" {"test/jose_test.ml"}
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/test/jose_test__Fixtures.cmi" {"test/jose_test__Fixtures.cmi"}
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/test/jose_test__Fixtures.cmt" {"test/jose_test__Fixtures.cmt"}
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/test/jose_test__Fixtures.cmx" {"test/jose_test__Fixtures.cmx"}
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/test/jose_test__JWKTest.cmi" {"test/jose_test__JWKTest.cmi"}
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/test/jose_test__JWKTest.cmt" {"test/jose_test__JWKTest.cmt"}
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/test/jose_test__JWKTest.cmx" {"test/jose_test__JWKTest.cmx"}
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/test/jose_test__JWTTest.cmi" {"test/jose_test__JWTTest.cmi"}
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/test/jose_test__JWTTest.cmt" {"test/jose_test__JWTTest.cmt"}
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/lib/jose/test/jose_test__JWTTest.cmx" {"test/jose_test__JWTTest.cmx"}
]
bin: [
  "/Users/ulrik.strid/Projects/reason-native-web/reason-jose/_esy/default/store/b/reason_native_web__s__jose-14f8c102/install/default/bin/RunTests.exe"
]
