name: Build master - Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false


      - uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v10
        with:
          name: anmonteiro

      - name: "Check nix flake "
        run: nix flake check

      - name: Build
        run: nix develop -c dune build -p jose

      - name: Test with coverage
        run: nix develop -c dune build @runtest --instrument-with bisect_ppx --force

      - name: Upload coverage
        run: nix develop -c bisect-ppx-report send-to Codecov

      - name: Build docs
        run: nix develop -c dune build @doc

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          CLEAN: true
          FOLDER: _build/default/_doc/_html
