name: Check PR

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false


      - uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v10
        with:
          name: anmonteiro

      - name: "Check nix flake "
        run: nix flake check

      - name: Build
        run: nix develop -c dune build -p jose

      - name: Test with coverage
        run: nix develop -c dune build @runtest

      - name: Build docs
        run: nix develop -c dune build @doc