name: Check PR

on:
  pull_request:
    branches:
    - master

jobs:
  opam:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-compiler:
          - 4.13.x
          - 4.08.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v10
        with:
          name: anmonteiro

      - name: Build
        run: nix develop --accept-flake-config -c dune build

      - name: Test with coverage
        run: nix develop --accept-flake-config -c dune build @runtest --instrument-with bisect_ppx --force

      - name: Upload coverage
        run: nix develop --accept-flake-config -c bisect-ppx-report send-to Codecov

      - name: Build docs
        run: nix develop --accept-flake-config -c dune build @doc